# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Logstash Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-logstash
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-logstash
  template:
    metadata:
      labels:
        app: wazuh-logstash
      name: wazuh-logstash
    spec:
      containers:
        - name: wazuh-logstash
          image: 'wazuh/wazuh-logstash:3.8.0_6.5.4'
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1.5Gi
          env:
            - name: LS_JAVA_OPTS
              value: '-Xmx1g -Xms512m'
          ports:
            - containerPort: 5000
