# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

secretGenerator:
  - name: indexer-certs
    files:
      - config/indexer/certs/admin-key.pem
      - config/indexer/certs/admin.pem
      - config/indexer/certs/indexer-key.pem
      - config/indexer/certs/indexer.pem
      - config/indexer/certs/root-ca.pem
  - name: dashboard-certs
    files:
      - config/dashboard/certs/dashboard-key.pem
      - config/dashboard/certs/dashboard.pem
      - config/dashboard/certs/root-ca.pem
  - name: manager-certs
    files:
      - config/manager/certs/manager-key.pem
      - config/manager/certs/manager.pem
      - config/manager/certs/root-ca.pem

resources:
  - base/wazuh-ns.yaml
  - base/storage-class.yaml
  - base/middleware.yaml
  - base/ingressRoute-tcp-dashboard.yaml
  - base/ingressRoute-tcp-events.yaml
  - base/ingressRoute-tcp-registration.yaml
  - base/Allow-DNS-np.yaml
  - base/default-deny-all.yaml

  - secrets/wazuh-api-cred-secret.yaml
  - secrets/wazuh-authd-pass-secret.yaml
  - secrets/wazuh-cluster-key-secret.yaml
  - secrets/dashboard-cred-secret.yaml
  - secrets/indexer-cred-secret.yaml

  - wazuh_managers/wazuh-cluster-svc.yaml
  - wazuh_managers/wazuh-events-svc.yaml
  - wazuh_managers/wazuh-registration-svc.yaml
  - wazuh_managers/wazuh-api-svc.yaml
  - wazuh_managers/wazuh-master-sts.yaml
  - wazuh_managers/wazuh-worker-sts.yaml
  - wazuh_managers/network-policies/manager-egress.yaml
  - wazuh_managers/network-policies/manager-egress-external.yaml
  - wazuh_managers/network-policies/wazuh-master-ingress.yaml
  - wazuh_managers/network-policies/wazuh-worker-egress.yaml

  - indexer_stack/wazuh-indexer/indexer-svc.yaml
  - indexer_stack/wazuh-indexer/indexer-egress.yaml
  - indexer_stack/wazuh-indexer/indexer-ingress.yaml
  - indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

  - indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
  - indexer_stack/wazuh-dashboard/dashboard-svc.yaml
  - indexer_stack/wazuh-dashboard/dashboard-egress.yaml
