# Copyright (C) 2021 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Elasticsearch service: API

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: wazuh
  labels:
    app: wazuh-elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: wazuh-elasticsearch
  ports:
    - name: es-rest
      port: 9200
      targetPort: 9200
