# Copyright (C) 2021 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Elasticsearch StatefulSet: 3 master nodes.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wazuh-elasticsearch
  serviceName: wazuh-elasticsearch
  template:
    metadata:
      labels:
        app: wazuh-elasticsearch
      name: wazuh-elasticsearch
    spec:
      # Set the wazuh-elasticsearch volume permissions so the elasticsearch user can use it
      volumes:
        - name: odfe-ssl-certs
          secret:
            secretName: odfe-ssl-certs
        - name: elastic-odfe-conf
          configMap:
            name: elastic-odfe-conf
      initContainers:
        - name: volume-mount-hack
          image: busybox
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          command:
            - sh
            - '-c'
            - 'chown -R 1000:1000 /usr/share/elasticsearch/data'
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-elasticsearch
          image: 'amazon/opendistro-for-elasticsearch:1.13.2'
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: ES_JAVA_OPTS
              value: '-Xms1g -Xmx1g'
            - name: CLUSTER_NAME
              value: wazuh
            - name: NETWORK_HOST
              value: "0.0.0.0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: wazuh-elasticsearch
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: 'true'
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: wazuh-elasticsearch
              mountPath: /usr/share/elasticsearch/data
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/node-key.pem
              subPath: node-key.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/node.pem
              subPath: node.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/admin.pem
              subPath: admin.pem
              readOnly: true
            - name: odfe-ssl-certs
              mountPath: /usr/share/elasticsearch/config/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
            - name: elastic-odfe-conf
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: elastic-odfe-conf
              mountPath: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
              subPath: internal_users.yml
              readOnly: true
          ports:
            - containerPort: 9200
              name: es-rest
            - containerPort: 9300
              name: es-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-elasticsearch
        namespace: es-cluster
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wazuh-storage
        resources:
          requests:
            storage: 500Mi
