name: 'Setup and Presign S3 Artifacts'
description: 'Download the test artifacts URIs file from S3, process it to replace variables, and generate presigned URLs for each artifact.'

inputs:
  aws-region:
    description: 'AWS region where the S3 bucket is located'
    required: true
    default: 'us-west-1'
  s3-bucket-artifacts:
    description: 'S3 bucket name where artifacts are stored'
    required: true
  artifact-urls-file-temp:
    description: 'Temporary file path for artifact URLs'
    required: true
    default: '/tmp/artifact_urls.yml'
  wazuh-version:
    description: 'Wazuh version'
    required: true
  wazuh-major:
    description: 'Wazuh major version'
    required: true
  assistant_revision:
    description: 'Assistant revision'
    required: true
  indexer_commit:
    description: 'Indexer commit'
    required: true
  manager_commit:
    description: 'Manager commit'
    required: true
  dashboard_commit:
    description: 'Dashboard commit'
    required: true
  agent_commit:
    description: 'Agent commit'
    required: true
  ova_revision:
    description: 'OVA revision'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download S3 package URIs file
      shell: bash
      run: |
        mkdir -p "$(dirname "${{ inputs.artifact-urls-file-temp }}")"
        S3_KEY="deployment/artifact_urls.yml"
        aws s3 cp "s3://${{ inputs.s3-bucket-artifacts }}/$S3_KEY" "${{ inputs.artifact-urls-file-temp }}" --region ${{ inputs.aws-region }}

    - name: Generate the variables file
      shell: bash
      env:
        WAZUH_VERSION: ${{ inputs.wazuh-version }}
        WAZUH_MAJOR: ${{ inputs.wazuh-major }}
        ARTIFACT_URLS_FILE_TEMP: ${{ inputs.artifact-urls-file-temp }}
        ASSISTANT_REVISION: ${{ inputs.assistant_revision }}
        INDEXER_COMMIT: ${{ inputs.indexer_commit }}
        MANAGER_COMMIT: ${{ inputs.manager_commit }}
        DASHBOARD_COMMIT: ${{ inputs.dashboard_commit }}
        AGENT_COMMIT: ${{ inputs.agent_commit }}
        OVA_REVISION: ${{ inputs.ova_revision }}
      run: |
        OUTPUT_FILE="/tmp/wazuh-docker/artifact_urls_processed.yml"
        PRESIGNED_OUTPUT_FILE="/tmp/wazuh-docker/artifact_urls_presigned.yml"
        mkdir -p "$(dirname "$OUTPUT_FILE")"

        : > "$OUTPUT_FILE"
        : > "$PRESIGNED_OUTPUT_FILE"

        # Verify if the input file exists
        if [ ! -f "$ARTIFACT_URLS_FILE_TEMP" ]; then
          echo "The input file $ARTIFACT_URLS_FILE_TEMP does not exist." >&2
          exit 1
        fi

        # Process the file line by line (replacing ocurrences)
        while IFS= read -r line || [ -n "$line" ]; do
          # Skip empty lines and comments
          if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            echo "$line" >> "$OUTPUT_FILE"
            continue
          fi

          # Replace variables with their actual values
          line=${line//\$\{\{ vars.AWS_S3_BUCKET_DEV \}\}/${{ vars.AWS_S3_BUCKET_DEV }}}
          line=${line//\$\{\{ env.MAJOR \}\}/${{ env.WAZUH_MAJOR }}}
          line=${line//\$\{\{ env.WAZUH_VERSION \}\}/${{ env.WAZUH_VERSION }}}

          # Replace component revisions
          line=${line//\$\{\{ env.ASSISTANT_REVISION \}\}/${{ env.ASSISTANT_REVISION }}}
          line=${line//\$\{\{ env.INDEXER_REVISION \}\}/${{ env.INDEXER_COMMIT }}}
          line=${line//\$\{\{ env.MANAGER_REVISION \}\}/${{ env.MANAGER_COMMIT }}}
          line=${line//\$\{\{ env.DASHBOARD_REVISION \}\}/${{ env.DASHBOARD_COMMIT }}}
          line=${line//\$\{\{ env.AGENT_REVISION \}\}/${{ env.AGENT_COMMIT }}}
          line=${line//\$\{\{ env.OVA_REVISION \}\}/${{ env.OVA_REVISION }}}

          # Append the processed line to the output file
          echo "$line" >> "$OUTPUT_FILE"
        done < "$ARTIFACT_URLS_FILE_TEMP"

        # Verify the output file
        if [ -f "$OUTPUT_FILE" ]; then
          echo "The downloaded file artifact_urls.yml was successfully processed at $OUTPUT_FILE."
        else
          echo "Failed to create processed artifact_urls.yml file." >&2
          exit 1
        fi

        # Generate the presigned URLs for each package
        while IFS= read -r line || [ -n "$line" ]; do
          # Skip empty lines and comments
          if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            echo "$line" >> "$PRESIGNED_OUTPUT_FILE"
            continue
          fi

          # Extract both package_name and package_s3_uri from the line
          if [[ "$line" =~ ^([a-zA-Z0-9_]+):[[:space:]]*\"?s3://([^\"[:space:]]+) ]]; then
            PACKAGE_NAME="${BASH_REMATCH[1]}"
            PACKAGE_S3_URI="s3://${BASH_REMATCH[2]}"

            # Check if the object exists in S3
            BUCKET_NAME=$(echo "$PACKAGE_S3_URI" | cut -d '/' -f 3)
            OBJ_KEY=$(echo "$PACKAGE_S3_URI" | cut -d '/' -f 4-)
            if ! aws s3api head-object --bucket "$BUCKET_NAME" --key "$OBJ_KEY" --region us-west-1 > /dev/null 2>&1; then
              echo "Object $PACKAGE_S3_URI does not exist. Skipping..." >&2
              continue
            fi

            # Generate a pre-signed URL for the S3 URI
            echo "Generating pre-signed URL for $PACKAGE_NAME..."
            PRESIGNED_URL=$(aws s3 presign "$PACKAGE_S3_URI" --expires-in 43200 --region us-west-1)
            presigned_url_line="$PACKAGE_NAME: \"$PRESIGNED_URL\""

            # Append the processed line to the output file
            echo "$presigned_url_line" >> "$PRESIGNED_OUTPUT_FILE"
          else
            echo "$line" >> "$PRESIGNED_OUTPUT_FILE"

            echo "Skipping line for presigning (no S3 URI found):"
            echo "$line"
          fi
        done < "$OUTPUT_FILE"

        # Verify the presigned urls file
        if [ -f "$PRESIGNED_OUTPUT_FILE" ]; then
          echo "Presigned URLs file created successfully at $PRESIGNED_OUTPUT_FILE."
        else
          echo "Failed to create presigned artifact_urls.yml file." >&2
          exit 1
        fi
        
        # Export variables to the environment
        awk -F':' '!/^#/ && NF>1 {name=$1; val=substr($0,length(name)+3); gsub(/[-.]/,"_",name); print name "=" val}' $PRESIGNED_OUTPUT_FILE >> $GITHUB_ENV