apiVersion: v1
kind: Service
metadata:
  name: proxy-https
spec:
  ports:
  - name: https
    nodePort: 31337
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: proxy
  sessionAffinity: None
  type: NodePort