# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh workers StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: worker
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: worker
      name: wazuh-manager-worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: wazuh-manager
                    node-type: worker
      volumes:
        - name: wazuh-manager-certs
          secret:
            secretName: manager-certs
      initContainers:
        - name: init-wazuh-etc
          image: 'wazuh/wazuh-manager:5.0.0'
          command:
            - /bin/sh
            - -c
            - |
              if [ -z "$(ls -A /pvc-etc)" ]; then
                cp -a /var/wazuh-manager/etc/* /pvc-etc/
              fi
          volumeMounts:
            - name: wazuh-manager-worker
              mountPath: /pvc-etc
              subPath: wazuh/var/wazuh-manager/etc
      securityContext:
        fsGroup: 101
      containers:
        - name: wazuh-manager
          image: 'wazuh/wazuh-manager:5.0.0'
          resources:
            limits:
              cpu: 400m
              memory: 1280Mi
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/api/configuration
              subPath: wazuh/var/wazuh-manager/api/configuration
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/etc
              subPath: wazuh/var/wazuh-manager/etc
            - name: wazuh-manager-certs
              mountPath: /var/wazuh-manager/etc/certs/root-ca.pem
              readOnly: true
              subPath: root-ca.pem
            - name: wazuh-manager-certs
              mountPath: /var/wazuh-manager/etc/certs/manager.pem
              subPath: manager.pem
              readOnly: true
            - name: wazuh-manager-certs
              mountPath: /var/wazuh-manager/etc/certs/manager-key.pem
              subPath: manager-key.pem
              readOnly: true
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/logs
              subPath: wazuh/var/wazuh-manager/logs
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/queue
              subPath: wazuh/var/wazuh-manager/queue
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/var/multigroups
              subPath: wazuh/var/wazuh-manager/var/multigroups
            - name: wazuh-manager-worker
              mountPath: /var/wazuh-manager/active-response/bin
              subPath: wazuh/var/wazuh-manager/active-response/bin
          ports:
            - containerPort: 1514
              name: agents-events
            - containerPort: 1516
              name: cluster
          env:
            - name: WAZUH_INDEXER_HOSTS
              value: 'wazuh-indexer:9200'
            - name: WAZUH_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WAZUH_NODE_TYPE
              value: 'worker'
            - name: WAZUH_CLUSTER_BIND_ADDR
              value: '0.0.0.0'
            - name: WAZUH_CLUSTER_NODES
              value: 'wazuh-cluster'
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: password
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /var/wazuh-manager/etc/certs/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /var/wazuh-manager/etc/certs/manager.pem
            - name: SSL_KEY
              value: /var/wazuh-manager/etc/certs/manager-key.pem
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
  volumeClaimTemplates:
    - metadata:
        name: wazuh-manager-worker
        namespace: wazuh
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: wazuh-storage
        resources:
          requests:
            storage: 500Mi
