kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: wazuh

resources:
  - ../../wazuh/base
  - ../../wazuh/secrets
  - ../../wazuh/wazuh_managers
  - ../../wazuh/certs
  - ../../wazuh/indexer_stack
