# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Kibana Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      containers:
        - name: wazuh-kibana
          image: 'wazuh/wazuh-kibana:3.8.0_6.5.4'
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 1024Mi
          ports:
            - containerPort: 5601
              name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: 'http://elasticsearch:9200'
            - name: NODE_OPTIONS
              value: '--max-old-space-size=512'
            - name: WAZUH_SHARDS
              value: '1'
            - name: WAZUH_REPLICAS
              value: '0'
            - name: WAZUH_VERSION_SHARDS
              value: '1'
            - name: WAZUH_VERSION_REPLICAS
              value: '0'
            - name: WAZUH_MONITORING_SHARDS
              value: '1'
            - name: WAZUH_MONITORING_REPLICAS
              value: '0'
