---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
  namespace: wazuh
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-pki-ca
  namespace: wazuh
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: selfsigning-issuer
  secretName: wazuh-pki-ca
  commonName: "wazuh-ca"
  subject:
    organizations:
      - "Wazuh, Inc."
  usages:
    - "signing"
    - "key encipherment"
    - "cert sign"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: wazuh-issuer
  namespace: wazuh
spec:
  ca:
    secretName: "wazuh-pki-ca"
